### ISSUE TITLE
prepGluster not parsing BrickDevice JSON Entry

### ISSUE THREAD

**Issue by wattsteve** [pcuzner/docker-gluster-centos#3]
Despite the fact that the BrickDevice is in the JSON, it seems that its not being picked up in the JSON Parsing logic in prepGluster.

[root@master gluster-configs]# cat atomic-1.json
{
  "HostName": "worker-1",
  "GlusterNodeName": "gluster-1",
  "IPAddress": "192.168.58.21/24",
  "BrickDevice": "/dev/sdb",
  "ZapDevice": "true",
  "PeerList": [{ "IP": 192.168.58.22"}]
}

[root@worker-1 ~]# curl -s http://192.168.58.20:2379/v2/keys/gluster/config/worker-1
{"action":"get","node":{"key":"/gluster/config/worker-1","value":"{\n  \"HostName\": \"worker-1\",\n  \"GlusterNodeName\": \"gluster-1\",\n  \"IPAddress\": \"192.168.58.21/24\",\n  \"BrickDevice\": \"/dev/sdb\",\n  \"ZapDevice\": \"true\",\n  \"PeerList\": [{ \"IP\": 192.168.58.22\"}]\n}","modifiedIndex":2012,"createdIndex":2012}}

[root@worker-1 docker-gluster-centos]# ./prepHost.sh -t gluster

Checking configuration directories
- glusterfs directories already present, nothing to do

Checking for etcd service
- etcd service found on 192.168.58.20
- retrieving this hosts intended config from etcd
  Brick Device setting:

Config does not provide any disk information, nothing to do

**Comment by pcuzner** [comment]
peer list IP is not enclosed by " - resulting in the json not parsing correctly
