### ISSUE TITLE
Dockerfile does not compile

### ISSUE THREAD

**Issue by wattsteve** [pcuzner/docker-gluster-centos#4]
[root@master docker-gluster-centos]# docker build /opt/docker-gluster-centos/
Sending build context to Docker daemon 243.7 kB
Sending build context to Docker daemon 
Step 0 : FROM centos:latest
 ---> 0f73ae75014f
Step 1 : MAINTAINER Paul Cuzner pcuzner@redhat.com
 ---> Using cache
 ---> 1bf802b49244
Step 2 : ENV container docker
 ---> Using cache
 ---> 3e6c72e1b5d5
Step 3 : RUN yum -y install systemd systemd-libs
 ---> Running in 93fe0a43b8fc
Loaded plugins: fastestmirror

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

```
 1. Contact the upstream for the repository and get them to fix the problem.

 2. Reconfigure the baseurl/etc. for the repository, to point to a working
    upstream. This is most often useful if you are using a newer
    distribution release than is supported by the repository (and the
    packages for the previous distribution release still work).

 3. Disable the repository, so yum won't use it by default. Yum will then
    just ignore the repository until you permanently enable it again or use
    --enablerepo for temporary usage:

        yum-config-manager --disable <repoid>

 4. Configure the failing repository to be skipped, if it is unavailable.
    Note that yum will try to contact the repo. when it runs most commands,
    so will have to try and fail each time (and thus. yum will be be much
    slower). If it is a very temporary problem though, this is often a nice
    compromise:

        yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true
```

Cannot find a valid baseurl for repo: base/7/x86_64
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
The command '/bin/sh -c yum -y install systemd systemd-libs' returned a non-zero code: 1

**Comment by wattsteve** [comment]
@pcuzner Perhaps you could push a working image to the Docker Hub so the team can skip the build aspect for now?

**Comment by pcuzner** [comment]
Agree - let's not get bogged down on the build. The image is uploaded to docker hub - 
docker pull pcuzner/glusterfs-centos

Closing issue.
